### ISSUE TITLE
Support for MacOS

### ISSUE THREAD

**Issue by lperozzi** [waynegm/OpendTect-Plugins#46]
HI @waynegm, 

first many thanks for your work that is awesome. We are able to install your plugins on OpendTect Mac version? I tried to follow the same procedure than for Linux but without success.

Many thanks

Lorenzo

**Comment by waynegm** [comment]
Hi,
Due to time and resource limitations I only publish binary builds of my plugins for Linux and Windows. The Linux binaries won't work on MacOS. 

Some time ago dGB stopped including an option to generate a  plugin development environment for MacOS  because it was too difficult to maintain given the size of the user base. It should still be possible to build plugins on MacOS but it will require building OpendTect from source code. 

So your options are:
- Build OpendTect and my plugins from source code
- Run Linux or Windows in a Virtual Machine and install OpendTect 
- Set your workstation up to dual boot MacOS and Linux/Windows
Regards,
Wayne
